#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceApplication
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShopBanGiayPro")]
	public partial class DataClassesShopBanGiayProDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertct_hoadon(ct_hoadon instance);
    partial void Updatect_hoadon(ct_hoadon instance);
    partial void Deletect_hoadon(ct_hoadon instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertct_phieunhap(ct_phieunhap instance);
    partial void Updatect_phieunhap(ct_phieunhap instance);
    partial void Deletect_phieunhap(ct_phieunhap instance);
    partial void Insertct_sanpham(ct_sanpham instance);
    partial void Updatect_sanpham(ct_sanpham instance);
    partial void Deletect_sanpham(ct_sanpham instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertloai(loai instance);
    partial void Updateloai(loai instance);
    partial void Deleteloai(loai instance);
    partial void Insertnhasx(nhasx instance);
    partial void Updatenhasx(nhasx instance);
    partial void Deletenhasx(nhasx instance);
    partial void Insertphieunhap(phieunhap instance);
    partial void Updatephieunhap(phieunhap instance);
    partial void Deletephieunhap(phieunhap instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Inserttonkho(tonkho instance);
    partial void Updatetonkho(tonkho instance);
    partial void Deletetonkho(tonkho instance);
    #endregion
		
		public DataClassesShopBanGiayProDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShopBanGiayProConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesShopBanGiayProDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesShopBanGiayProDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesShopBanGiayProDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesShopBanGiayProDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ct_hoadon> ct_hoadons
		{
			get
			{
				return this.GetTable<ct_hoadon>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<ct_phieunhap> ct_phieunhaps
		{
			get
			{
				return this.GetTable<ct_phieunhap>();
			}
		}
		
		public System.Data.Linq.Table<ct_sanpham> ct_sanphams
		{
			get
			{
				return this.GetTable<ct_sanpham>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<loai> loais
		{
			get
			{
				return this.GetTable<loai>();
			}
		}
		
		public System.Data.Linq.Table<nhasx> nhasxes
		{
			get
			{
				return this.GetTable<nhasx>();
			}
		}
		
		public System.Data.Linq.Table<phieunhap> phieunhaps
		{
			get
			{
				return this.GetTable<phieunhap>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<tonkho> tonkhos
		{
			get
			{
				return this.GetTable<tonkho>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ct_hoadon")]
	public partial class ct_hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mahd;
		
		private string _masp;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<double> _thanhtien;
		
		private EntityRef<hoadon> _hoadon;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnthanhtienChanging(System.Nullable<double> value);
    partial void OnthanhtienChanged();
    #endregion
		
		public ct_hoadon()
		{
			this._hoadon = default(EntityRef<hoadon>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					if (this._hoadon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Float")]
		public System.Nullable<double> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_ct_hoadon", Storage="_hoadon", ThisKey="mahd", OtherKey="mahd", IsForeignKey=true)]
		public hoadon hoadon
		{
			get
			{
				return this._hoadon.Entity;
			}
			set
			{
				hoadon previousValue = this._hoadon.Entity;
				if (((previousValue != value) 
							|| (this._hoadon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoadon.Entity = null;
						previousValue.ct_hoadons.Remove(this);
					}
					this._hoadon.Entity = value;
					if ((value != null))
					{
						value.ct_hoadons.Add(this);
						this._mahd = value.mahd;
					}
					else
					{
						this._mahd = default(string);
					}
					this.SendPropertyChanged("hoadon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_ct_hoadon", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.ct_hoadons.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.ct_hoadons.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(string);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _password;
		
		private string _hoten;
		
		private System.Nullable<bool> _gioitinhnam;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _diachi;
		
		private string _sdt;
		
		private string _hinh;
		
		private string _email;
		
		private string _quyenhang;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OngioitinhnamChanging(System.Nullable<bool> value);
    partial void OngioitinhnamChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnquyenhangChanging(string value);
    partial void OnquyenhangChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public user()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinhnam", DbType="Bit")]
		public System.Nullable<bool> gioitinhnam
		{
			get
			{
				return this._gioitinhnam;
			}
			set
			{
				if ((this._gioitinhnam != value))
				{
					this.OngioitinhnamChanging(value);
					this.SendPropertyChanging();
					this._gioitinhnam = value;
					this.SendPropertyChanged("gioitinhnam");
					this.OngioitinhnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(MAX)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Char(11)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="NVarChar(MAX)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyenhang", DbType="VarChar(50)")]
		public string quyenhang
		{
			get
			{
				return this._quyenhang;
			}
			set
			{
				if ((this._quyenhang != value))
				{
					this.OnquyenhangChanging(value);
					this.SendPropertyChanging();
					this._quyenhang = value;
					this.SendPropertyChanged("quyenhang");
					this.OnquyenhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_hoadon", Storage="_hoadons", ThisKey="username", OtherKey="username")]
		internal EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ct_phieunhap")]
	public partial class ct_phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mapn;
		
		private string _masp;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<double> _gia;
		
		private System.Nullable<double> _thanhtien;
		
		private EntityRef<phieunhap> _phieunhap;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmapnChanging(string value);
    partial void OnmapnChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OnthanhtienChanging(System.Nullable<double> value);
    partial void OnthanhtienChanged();
    #endregion
		
		public ct_phieunhap()
		{
			this._phieunhap = default(EntityRef<phieunhap>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapn", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string mapn
		{
			get
			{
				return this._mapn;
			}
			set
			{
				if ((this._mapn != value))
				{
					if (this._phieunhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmapnChanging(value);
					this.SendPropertyChanging();
					this._mapn = value;
					this.SendPropertyChanged("mapn");
					this.OnmapnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Float")]
		public System.Nullable<double> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieunhap_ct_phieunhap", Storage="_phieunhap", ThisKey="mapn", OtherKey="mapn", IsForeignKey=true)]
		public phieunhap phieunhap
		{
			get
			{
				return this._phieunhap.Entity;
			}
			set
			{
				phieunhap previousValue = this._phieunhap.Entity;
				if (((previousValue != value) 
							|| (this._phieunhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieunhap.Entity = null;
						previousValue.ct_phieunhaps.Remove(this);
					}
					this._phieunhap.Entity = value;
					if ((value != null))
					{
						value.ct_phieunhaps.Add(this);
						this._mapn = value.mapn;
					}
					else
					{
						this._mapn = default(string);
					}
					this.SendPropertyChanged("phieunhap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_ct_phieunhap", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.ct_phieunhaps.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.ct_phieunhaps.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(string);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ct_sanpham")]
	public partial class ct_sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _masp;
		
		private string _xuatxu;
		
		private string _mausac;
		
		private string _kieudang;
		
		private string _chatlieu;
		
		private string _mota;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OnxuatxuChanging(string value);
    partial void OnxuatxuChanged();
    partial void OnmausacChanging(string value);
    partial void OnmausacChanged();
    partial void OnkieudangChanging(string value);
    partial void OnkieudangChanged();
    partial void OnchatlieuChanging(string value);
    partial void OnchatlieuChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    #endregion
		
		public ct_sanpham()
		{
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuatxu", DbType="NVarChar(MAX)")]
		public string xuatxu
		{
			get
			{
				return this._xuatxu;
			}
			set
			{
				if ((this._xuatxu != value))
				{
					this.OnxuatxuChanging(value);
					this.SendPropertyChanging();
					this._xuatxu = value;
					this.SendPropertyChanged("xuatxu");
					this.OnxuatxuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mausac", DbType="NVarChar(MAX)")]
		public string mausac
		{
			get
			{
				return this._mausac;
			}
			set
			{
				if ((this._mausac != value))
				{
					this.OnmausacChanging(value);
					this.SendPropertyChanging();
					this._mausac = value;
					this.SendPropertyChanged("mausac");
					this.OnmausacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kieudang", DbType="NVarChar(MAX)")]
		public string kieudang
		{
			get
			{
				return this._kieudang;
			}
			set
			{
				if ((this._kieudang != value))
				{
					this.OnkieudangChanging(value);
					this.SendPropertyChanging();
					this._kieudang = value;
					this.SendPropertyChanged("kieudang");
					this.OnkieudangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chatlieu", DbType="NVarChar(MAX)")]
		public string chatlieu
		{
			get
			{
				return this._chatlieu;
			}
			set
			{
				if ((this._chatlieu != value))
				{
					this.OnchatlieuChanging(value);
					this.SendPropertyChanging();
					this._chatlieu = value;
					this.SendPropertyChanged("chatlieu");
					this.OnchatlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_ct_sanpham", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.ct_sanphams.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.ct_sanphams.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(string);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mahd;
		
		private string _username;
		
		private System.Nullable<System.DateTime> _ngaymua;
		
		private System.Nullable<bool> _hoanthanh;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<ct_hoadon> _ct_hoadons;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnngaymuaChanging(System.Nullable<System.DateTime> value);
    partial void OnngaymuaChanged();
    partial void OnhoanthanhChanging(System.Nullable<bool> value);
    partial void OnhoanthanhChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public hoadon()
		{
			this._ct_hoadons = new EntitySet<ct_hoadon>(new Action<ct_hoadon>(this.attach_ct_hoadons), new Action<ct_hoadon>(this.detach_ct_hoadons));
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaymua", DbType="Date")]
		public System.Nullable<System.DateTime> ngaymua
		{
			get
			{
				return this._ngaymua;
			}
			set
			{
				if ((this._ngaymua != value))
				{
					this.OnngaymuaChanging(value);
					this.SendPropertyChanging();
					this._ngaymua = value;
					this.SendPropertyChanged("ngaymua");
					this.OnngaymuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoanthanh", DbType="Bit")]
		public System.Nullable<bool> hoanthanh
		{
			get
			{
				return this._hoanthanh;
			}
			set
			{
				if ((this._hoanthanh != value))
				{
					this.OnhoanthanhChanging(value);
					this.SendPropertyChanging();
					this._hoanthanh = value;
					this.SendPropertyChanged("hoanthanh");
					this.OnhoanthanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoadon_ct_hoadon", Storage="_ct_hoadons", ThisKey="mahd", OtherKey="mahd")]
		internal EntitySet<ct_hoadon> ct_hoadons
		{
			get
			{
				return this._ct_hoadons;
			}
			set
			{
				this._ct_hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_hoadon", Storage="_user", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ct_hoadons(ct_hoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon = this;
		}
		
		private void detach_ct_hoadons(ct_hoadon entity)
		{
			this.SendPropertyChanging();
			entity.hoadon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loai")]
	public partial class loai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _maloai;
		
		private string _ten;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public loai()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_sanpham", Storage="_sanphams", ThisKey="maloai", OtherKey="maloai")]
		internal EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loai = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.loai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhasx")]
	public partial class nhasx : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mansx;
		
		private string _ten;
		
		private string _diachi;
		
		private string _hinh;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmansxChanging(string value);
    partial void OnmansxChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public nhasx()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mansx", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mansx
		{
			get
			{
				return this._mansx;
			}
			set
			{
				if ((this._mansx != value))
				{
					this.OnmansxChanging(value);
					this.SendPropertyChanging();
					this._mansx = value;
					this.SendPropertyChanged("mansx");
					this.OnmansxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(MAX)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="NVarChar(MAX)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhasx_sanpham", Storage="_sanphams", ThisKey="mansx", OtherKey="mansx")]
		internal EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.nhasx = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.nhasx = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieunhap")]
	public partial class phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mapn;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private System.Nullable<bool> _trangthai;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<ct_phieunhap> _ct_phieunhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmapnChanging(string value);
    partial void OnmapnChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    partial void OntrangthaiChanging(System.Nullable<bool> value);
    partial void OntrangthaiChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public phieunhap()
		{
			this._ct_phieunhaps = new EntitySet<ct_phieunhap>(new Action<ct_phieunhap>(this.attach_ct_phieunhaps), new Action<ct_phieunhap>(this.detach_ct_phieunhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapn", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mapn
		{
			get
			{
				return this._mapn;
			}
			set
			{
				if ((this._mapn != value))
				{
					this.OnmapnChanging(value);
					this.SendPropertyChanging();
					this._mapn = value;
					this.SendPropertyChanged("mapn");
					this.OnmapnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieunhap_ct_phieunhap", Storage="_ct_phieunhaps", ThisKey="mapn", OtherKey="mapn")]
		internal EntitySet<ct_phieunhap> ct_phieunhaps
		{
			get
			{
				return this._ct_phieunhaps;
			}
			set
			{
				this._ct_phieunhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ct_phieunhaps(ct_phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.phieunhap = this;
		}
		
		private void detach_ct_phieunhaps(ct_phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.phieunhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _masp;
		
		private string _maloai;
		
		private string _mansx;
		
		private string _tensp;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<double> _gia;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private string _hinh;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<ct_hoadon> _ct_hoadons;
		
		private EntitySet<ct_phieunhap> _ct_phieunhaps;
		
		private EntitySet<ct_sanpham> _ct_sanphams;
		
		private EntitySet<tonkho> _tonkhos;
		
		private EntityRef<loai> _loai;
		
		private EntityRef<nhasx> _nhasx;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OnmansxChanging(string value);
    partial void OnmansxChanged();
    partial void OntenspChanging(string value);
    partial void OntenspChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public sanpham()
		{
			this._ct_hoadons = new EntitySet<ct_hoadon>(new Action<ct_hoadon>(this.attach_ct_hoadons), new Action<ct_hoadon>(this.detach_ct_hoadons));
			this._ct_phieunhaps = new EntitySet<ct_phieunhap>(new Action<ct_phieunhap>(this.attach_ct_phieunhaps), new Action<ct_phieunhap>(this.detach_ct_phieunhaps));
			this._ct_sanphams = new EntitySet<ct_sanpham>(new Action<ct_sanpham>(this.attach_ct_sanphams), new Action<ct_sanpham>(this.detach_ct_sanphams));
			this._tonkhos = new EntitySet<tonkho>(new Action<tonkho>(this.attach_tonkhos), new Action<tonkho>(this.detach_tonkhos));
			this._loai = default(EntityRef<loai>);
			this._nhasx = default(EntityRef<nhasx>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._loai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mansx", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string mansx
		{
			get
			{
				return this._mansx;
			}
			set
			{
				if ((this._mansx != value))
				{
					if (this._nhasx.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmansxChanging(value);
					this.SendPropertyChanging();
					this._mansx = value;
					this.SendPropertyChanged("mansx");
					this.OnmansxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensp", DbType="NVarChar(50)")]
		public string tensp
		{
			get
			{
				return this._tensp;
			}
			set
			{
				if ((this._tensp != value))
				{
					this.OntenspChanging(value);
					this.SendPropertyChanging();
					this._tensp = value;
					this.SendPropertyChanged("tensp");
					this.OntenspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="NVarChar(MAX)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_ct_hoadon", Storage="_ct_hoadons", ThisKey="masp", OtherKey="masp")]
		internal EntitySet<ct_hoadon> ct_hoadons
		{
			get
			{
				return this._ct_hoadons;
			}
			set
			{
				this._ct_hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_ct_phieunhap", Storage="_ct_phieunhaps", ThisKey="masp", OtherKey="masp")]
		internal EntitySet<ct_phieunhap> ct_phieunhaps
		{
			get
			{
				return this._ct_phieunhaps;
			}
			set
			{
				this._ct_phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_ct_sanpham", Storage="_ct_sanphams", ThisKey="masp", OtherKey="masp")]
		internal EntitySet<ct_sanpham> ct_sanphams
		{
			get
			{
				return this._ct_sanphams;
			}
			set
			{
				this._ct_sanphams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_tonkho", Storage="_tonkhos", ThisKey="masp", OtherKey="masp")]
		internal EntitySet<tonkho> tonkhos
		{
			get
			{
				return this._tonkhos;
			}
			set
			{
				this._tonkhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loai_sanpham", Storage="_loai", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true)]
		public loai loai
		{
			get
			{
				return this._loai.Entity;
			}
			set
			{
				loai previousValue = this._loai.Entity;
				if (((previousValue != value) 
							|| (this._loai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loai.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._loai.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(string);
					}
					this.SendPropertyChanged("loai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhasx_sanpham", Storage="_nhasx", ThisKey="mansx", OtherKey="mansx", IsForeignKey=true)]
		public nhasx nhasx
		{
			get
			{
				return this._nhasx.Entity;
			}
			set
			{
				nhasx previousValue = this._nhasx.Entity;
				if (((previousValue != value) 
							|| (this._nhasx.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhasx.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._nhasx.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._mansx = value.mansx;
					}
					else
					{
						this._mansx = default(string);
					}
					this.SendPropertyChanged("nhasx");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ct_hoadons(ct_hoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_ct_hoadons(ct_hoadon entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_ct_phieunhaps(ct_phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_ct_phieunhaps(ct_phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_ct_sanphams(ct_sanpham entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_ct_sanphams(ct_sanpham entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_tonkhos(tonkho entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_tonkhos(tonkho entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tonkho")]
	public partial class tonkho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _masp;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private System.Nullable<int> _soluongton;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmaspChanging(string value);
    partial void OnmaspChanged();
    partial void OnngaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaycapnhatChanged();
    partial void OnsoluongtonChanging(System.Nullable<int> value);
    partial void OnsoluongtonChanged();
    #endregion
		
		public tonkho()
		{
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="Date")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this.OnngaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._ngaycapnhat = value;
					this.SendPropertyChanged("ngaycapnhat");
					this.OnngaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongton", DbType="Int")]
		public System.Nullable<int> soluongton
		{
			get
			{
				return this._soluongton;
			}
			set
			{
				if ((this._soluongton != value))
				{
					this.OnsoluongtonChanging(value);
					this.SendPropertyChanging();
					this._soluongton = value;
					this.SendPropertyChanged("soluongton");
					this.OnsoluongtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_tonkho", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.tonkhos.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.tonkhos.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(string);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
